### ISSUE TITLE
lsmas missing

### ISSUE THREAD

**Issue by miaoqiz** [Selur/VapoursynthScriptsInHybrid#3]
Hi there,

Thanks again for the wonderful scripts!

I followed the instructions and compiled the toolset and plugin on Ubuntu 22.04.

When I ran my script, here is an error:

----------------------------------------------------------

Python exception: No attribute with the name lsmas exists. Did you mistype a plugin namespace?

----------------------------------------------------------

When I looked into the "vs_plugin" folder, I did not see the "lsmash" library. 

Any help is much appreciated!

**Comment by Selur** [comment]
Problem is that https://github.com/Selur/hybrid-vapoursynth-addon/tree/master/build-plugins lacks a working build instruction for building vslsmashsource since HolyWu/L-SMASH-Works doesn't exist anymore.
Since I don't know how to build L-SMASH-Works,  for example from https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works, there is only 'plugin-vslsmashsource.sh.not.working'. see: https://github.com/Selur/hybrid-vapoursynth-addon/blob/master/build-plugins/plugin-vslsmashsource.sh.not.working
Not sure how I fix this.
If you use Hybrid, disabling 'Filtering->Misc->Source->Prefer LWLibAVSource over FFMpegSource2' and 'Prefer LSMASHSource over LWLibAVSource for mp4/mov' might help, since it should trigger Hybrid in most cases to use FFMpegSource2 instead of LWLibAVSource  and LSMASHSource  and thus not require 'lsmas'.

If someone finds a way to fix 'plugin-vslsmashsource.sh', let me know, since atm. this is the main reason there is no new Hybrid release.

Cu Selur

**Comment by miaoqiz** [comment]
Thanks very much! I appreciate it. 

I still have the previous version from 2 years ago, which works with "lsmas“. I just want to add "bestsource" plugin to the previous version, is it a way to do so? Thanks very much!

**Comment by Selur** [comment]
No, you can't add a new source filter to old Hybrid version.
Also: bestsource 'is still in the extremely experimental phase',...

**Comment by miaoqiz** [comment]
Thanks very much! I appreciate your quick response and information!

Have a good week!
